name: Workshop example Tag event workflow

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  clean_install_on_tag:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean install
        run: npm ci

  test_on_tag:
    needs: clean_install_on_tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install mocha
        run: npm install mocha -g
      - name: Run tests
        run: npm test

  publish_on_tag:
    needs: test_on_tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Publish
        run: bash publish.sh